kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "parksmap-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/tancheeyong/homework.git"
  strategy:
    jenkinsPipelineStrategy:
      env:
         - name: GUID
           value: ${GUID}
         - name: CLUSTER
           value: ${CLUSTER}
         - name: REPO
           value: ${REPO}
      jenkinsfilePath: ParksMap/Jenkinsfile
